version: '2'
services:
    cp-app:
        image: cp
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:mysql://cp-mysql:3306/cp?useUnicode=true&characterEncoding=utf8&useSSL=false
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
            - SPRING_DATA_ELASTICSEARCH_CLUSTER_NODES=cp-elasticsearch:9300
        ports:
            - 8080:8080
    cp-mysql:
        extends:
            file: mysql.yml
            service: cp-mysql
    cp-elasticsearch:
        extends:
            file: elasticsearch.yml
            service: cp-elasticsearch
